# Launch build environment
# Type:
# docker-compose run build-env

version: '2'

services:
  build-env:
    image: golang:alpine3.12
    volumes:
      - .:/go
    command: "sh -c 'apk add upx make && sh'"
  